// <auto-generated />
namespace TravelTripProje3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class mig_iletisim : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_iletisim));
        
        string IMigrationMetadata.Id
        {
            get { return "202206301855480_mig_iletisim"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
